---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    groups:
      npm:
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    groups:
      bundler:
