---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-workflows:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
    groups:
      npm-packages:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
    groups:
      bundler-packages:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: "/kubernetes"
    schedule:
      interval: "weekly"
    groups:
      k8s-manifests:
        patterns:
          - "*"
