name: Test github-script

on: workflow_dispatch

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: return {a:1, b:2}
      - name: Echo result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: Use result
        uses: actions/github-script@v7
        with:
          script: |
            const result = JSON.parse(`${{steps.set-result.outputs.result}}`);
            console.log(result.a)
            console.log(result.b)
            console.log(context)
                
