name: Test github-script

on: workflow_dispatch

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: return {a:1, b:2}
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
                
