name: Greetings Node

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        # renovate: datasource=endoflife-date depName=aws-lambda versioning=loose
        node-version: '18.x'
    - name: Print Node Version
      run: node --version
