name: Greetings Node

on: [pull_request, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
      with:
        # renovate: datasource=endoflife-date depName=aws-lambda versioning=loose
        node-version: '18.x'
    - name: Print Node Version
      run: node --version
    - name: Print Branch name
      run: echo ${{ github.head_ref || github.ref_name }}
