name: Renovate

# add manual trigger for testing
on: workflow_dispatch

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
